"""empty message

Revision ID: 0a2054aa83ed
Revises: 
Create Date: 2021-10-14 15:09:01.290745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2054aa83ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_open_date', sa.String(length=30), nullable=True),
    sa.Column('last_consulted_date', sa.String(length=30), nullable=True),
    sa.Column('vaccination_type', sa.String(length=5), nullable=True),
    sa.Column('doctor_consulted', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('post_code', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('active_customer', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details')
    # ### end Alembic commands ###
